### ISSUE TITLE
Using path-params in navigate-to fx

### ISSUE THREAD

**Issue by perkola** [ingesolvoll/kee-frame#92] opened 2020-05-19 18:20 UTC
Hi!
First of all I would like to thank you for this neat library. It has helped me set up several re-frame projects very quickly.

As per #64, using the `:navigate-to` effect does not work with the standard `:path-params` found in route data. As an example I am using a controller to redirect a user to the login page if they have yet not been authenticated:
```Clojure
(k/reg-controller
  :redirect-if-unauthorized
  {:params identity
   :start [:redirect-if-unauthorized]})

(rf/reg-event-fx
  :redirect-if-unauthorized
  (fn [{db :db} [_ route-data]]
    {:db (assoc db :requested-route route-data)
     ...}))
```
When The user has authenticated I want to redirect them to the original requested URL. I'm an expecting to do this using something like:
```Clojure
(rf/reg-event-fx
  :authorization-success
  (fn [{db :db} _]
    (let [route (get-in db [:requested-route :data :name])
          path-params (get-in db [:requested-route :path-params])]
      {:navigate-to [route path-params]})))   ; [:article {:id 42}]
```
since this follows the same pattern as `path-for` with a vector consisting of the route followed by the path params map:
```Clojure
(k/path-for [:article {:id 42}])
```
This does not work since the `match-data` fn looks for a `:query-string`. When supplying a query string on the format `article=42` the resulting route data on a redirect treats the query string as a hash and the route data looks like:
```Clojure
{:template "/",
 :data {:name :article},
 :result nil,
 :path-params {}, 
 :path "/", 
 :query-string nil, 
 :hash "?id=42"}
```
I am not sure where to move from here.

**Comment by ingesolvoll** [comment] 2020-05-26 20:54
@perkola So it seems the problem is that the built-in reitit router implementation does not convert from path-params to actual URL path. It should, and will be fixed when I get to it.

In the meantime, what you should do is roll your own router. See README for a guide, it's not hard. If everything goes well, maybe you could even create a PR with the path-params conversion :)

**Comment by ingesolvoll** [comment] 2020-07-12 20:19
See commit above, I created some tests for routers as a start. Things seem to roughly work for me, would you be able to see if you can create a failing case in the test?

The only thing you need to do is `lein test-refresh` and start editing the tests.

**Comment by j0hnnyblaz3** [comment] 2020-09-16 17:33
@ingesolvoll I was just wondering if this has been fixed? I am having the same issue. I would like to pass a re-direct to param so when a user logs in it will go back to the page they were trying to access. Thanks!

**Comment by ingesolvoll** [comment] 2020-10-14 09:28
@j0hnnyblaz3 @perkola 

I'm still trying to figure out what in particular is not working here. I tried switching the test app to use :navigate-to instead of path-for, and path params are encoded into urls as they should. Would any of you be able to insert a test that would fail in any of these?

https://github.com/ingesolvoll/kee-frame/blob/master/test/kee_frame/navigation_test.clj
https://github.com/ingesolvoll/kee-frame/blob/master/test/kee_frame/router_test.clj

This test in particular does what this issue seems to describe, or did I interpret it wrong? https://github.com/ingesolvoll/kee-frame/blob/master/test/kee_frame/navigation_test.clj#L12

**Comment by ingesolvoll** [comment] 2020-10-15 05:14
All fixes have been released now. I have no reason to believe I actually fixed these issues, other than being unable to reproduce. A failing test would be very useful.

**Closed** 2021-04-19 09:30 UTC
